question_manage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
]

quiz/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import QuizQuestionCreateView
from .views import QuizQuestionUpdateView

urlpatterns = [
    path('', views.index, name='index'),
    path('subjects/', views.subject_list, name='subject_list'),
    path('subjects/<int:subject_id>/', views.subject_detail, name='subject_detail'),
    path('fields/<int:field_id>/', views.field_questions, name='field_questions'),
    path('subject/<int:subject_id>/year/<int:year_id>/', views.year_questions, name='year_questions'),
    path('edit_subjects/', views.edit_subject_list, name='edit_subject_list'),
    path('edit_subjects/<int:subject_id>/', views.edit_subject_detail, name='edit_subject_detail'),
    path('edit_fields/<int:field_id>/', views.edit_field_questions, name='edit_field_questions'),
    path('edit_subject/<int:subject_id>/year/<int:year_id>/', views.edit_year_questions, name='edit_year_questions'),
    path('api/fields/', views.get_fields, name='get_fields'),
    path('Answer/<int:question_id>/', views.answer_question, name='answer_question'),
    path('upload/', views.extract_and_store_content, name='upload_document'),
    path('get_years/', views.get_years, name='get_years'),
    path('subject/<int:subject_id>/start_question/', views.start_question, name='start_question'),
    path('field/<int:field_id>/start_question/', views.start_question_field, name='start_question_field'),
    path('subject/<int:subject_id>/year/<int:year_id>/start_question/', views.start_question_year, name='start_question_year'),
    path('create_question/', QuizQuestionCreateView.as_view(), name='create_question'),
    path('update_question/<int:pk>/', QuizQuestionUpdateView.as_view(), name='update_question'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/models.py
from django.db import models
from adminsortable.models import SortableMixin
from adminsortable.fields import SortableForeignKey

class Grade(SortableMixin):
    name = models.CharField(max_length=30)
    the_order = models.PositiveIntegerField(default=0, editable=False, db_index=True)

    class Meta:
        ordering = ["the_order"]

    def __str__(self):
        return self.name

class Subject(SortableMixin):
    grade = SortableForeignKey(Grade, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    the_order = models.PositiveIntegerField(default=0, editable=False, db_index=True)

    class Meta:
        ordering = ["the_order"]

    def __str__(self):
        return self.name

class Field(SortableMixin):
    subject = SortableForeignKey(Subject, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    the_order = models.PositiveIntegerField(default=0, editable=False, db_index=True) # 追加する

    class Meta:
        ordering = ["the_order"]

    def __str__(self):
        return self.name

class Year(SortableMixin):
    year = models.IntegerField(unique=True)
    the_order = models.PositiveIntegerField(default=0, editable=False, db_index=True) # 追加する

    class Meta:
        ordering = ["the_order"]

    def __str__(self):
        return str(self.year)

class QuizQuestion(SortableMixin):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    field = SortableForeignKey(Field, on_delete=models.CASCADE, null=True, blank=True)
    question_text = models.CharField(max_length=1000)
    the_order = models.PositiveIntegerField(default=0, editable=False, db_index=True) # 追加する

    class Meta:
        ordering = ["the_order"]

    question_image = models.ImageField(upload_to='question_images/', null=True, blank=True)
    explanation = models.CharField(max_length=255, null=True, blank=True)
    explanation_image = models.ImageField(upload_to='explanation_images/', null=True, blank=True)

    def __str__(self):
        return f"{self.subject}-{self.field}-{self.explanation}-{self.question_text}"

class ChoiceExplanation(SortableMixin):
    question = SortableForeignKey(QuizQuestion, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255, null=True, blank=True)
    explanation_text = models.CharField(max_length=255, null=True, blank=True)
    isCorrect = models.BooleanField(default=False)
    the_order = models.PositiveIntegerField(default=0, editable=False, db_index=True) # 追加する

    class Meta:
        ordering = ["the_order"]

    def __str__(self):
        return f"問題:{self.question} 選択肢:{self.choice_text}"

class QuestionInstance(SortableMixin):
    question = SortableForeignKey(QuizQuestion, on_delete=models.CASCADE)
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    question_number = models.IntegerField()
    the_order = models.PositiveIntegerField(default=0, editable=False, db_index=True) # 追加する

    class Meta:
        ordering = ["the_order"]

    def __str__(self):
        return f"{self.question.subject}-{self.year}-{self.question_number} - {self.question.question_text}"

class Content(models.Model):
    title = models.CharField(max_length=255)  # レベル1のタイトル
    body = models.TextField()  # レベル1の本文

quiz/forms.py
from django import forms
from django.forms import formset_factory, modelformset_factory
from .models import QuizQuestion, ChoiceExplanation, QuestionInstance, Subject, Year, Field

class QuizQuestionForm(forms.ModelForm):

    question_text = forms.CharField(widget=forms.Textarea(attrs={'cols': '70', 'rows': '3'}))
    explanation = forms.CharField(widget=forms.Textarea(attrs={'cols': '70', 'rows': '3'}), required=False)

    class Meta:
        model = QuizQuestion
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # subjectフィールドから選択された値を取得
        selected_subject = self.initial.get('subject', None)
        # 関連するFieldのクエリセットをフィルタリングして設定
        self.fields['field'].queryset = Field.objects.filter(subject=selected_subject)

class ChoiceExplanationForm(forms.ModelForm):

    choice_text = forms.CharField(widget=forms.Textarea(attrs={'cols': '70', 'rows': '2'}))
    explanation_text = forms.CharField(widget=forms.Textarea(attrs={'cols': '70', 'rows': '2'}), required=False)

    class Meta:
        model = ChoiceExplanation
        fields = ['choice_text', 'explanation_text', 'isCorrect']

ChoiceExplanationFormSet = formset_factory(ChoiceExplanationForm, extra=5)
ChoiceExplanationFormSet2 = modelformset_factory(ChoiceExplanation, form=ChoiceExplanationForm, extra=0)


class QuestionInstanceForm(forms.ModelForm):
    class Meta:
        model = QuestionInstance
        fields = ['year', 'question_number']

QuestionInstanceFormSet = formset_factory(QuestionInstanceForm, extra=1)
QuestionInstanceFormSet2 = modelformset_factory(QuestionInstance, form=QuestionInstanceForm, extra=0)

class ContentUploadForm(forms.Form):
    subject = forms.ModelChoiceField(queryset=Subject.objects.all(), label='Subject')
    docx_file = forms.FileField(label='Upload DOCX File')

quiz/views.py
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from django.views.generic.edit import UpdateView, CreateView
from .forms import QuizQuestionForm, ContentUploadForm, ChoiceExplanationFormSet, QuestionInstanceFormSet, ChoiceExplanationFormSet2, QuestionInstanceFormSet2
from .models import QuizQuestion, ChoiceExplanation, QuestionInstance, Year, Subject, Field, Content, Grade
from django.http import JsonResponse
from docx import Document as DocxDocument
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
import re

def index(request):
    subjects = Subject.objects.all()
    return render(request, 'index.html', {'subjects': subjects})

def get_years(request):
    years = Year.objects.values('id', 'year')
    return JsonResponse({'years': list(years)})

def subject_list(request):
    grade_3_subjects = Subject.objects.filter(grade_id=1)
    grade_4_subjects = Subject.objects.filter(grade_id=2)
    return render(request, 'subject_list.html', {'grade_3_subjects': grade_3_subjects, 'grade_4_subjects': grade_4_subjects})

def subject_detail(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    fields = Field.objects.filter(subject=subject)
    years = Year.objects.filter(questioninstance__question__subject=subject).distinct()

    return render(request, 'subject_detail.html', {'subject': subject, 'fields': fields, 'years': years})

def field_questions(request, field_id):
    field = get_object_or_404(Field, pk=field_id)
    questions = QuizQuestion.objects.filter(field=field)
    for question in questions:
        question.correct_choices = [chr(i + 97) for i, choice in enumerate(question.choiceexplanation_set.all()) if choice.isCorrect]

    return render(request, 'field_questions.html', {'field': field, 'questions': questions})

def year_questions(request, subject_id, year_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    year = get_object_or_404(Year, pk=year_id)

    # QuestionInstance モデルを介して問題番号を取得
    question_instances = QuestionInstance.objects.filter(year=year, question__subject=subject).order_by('question_number')
    for question_instance in question_instances:
        question_instance.question.correct_choices = [chr(i + 97) for i, choice in enumerate(question_instance.question.choiceexplanation_set.all()) if choice.isCorrect]

    return render(request, 'year_questions.html', {'subject': subject, 'year': year, 'question_instances': question_instances})

def edit_subject_list(request):
    grade_3_subjects = Subject.objects.filter(grade_id=1)
    grade_4_subjects = Subject.objects.filter(grade_id=2)
    return render(request, 'edit_subject_list.html', {'grade_3_subjects': grade_3_subjects, 'grade_4_subjects': grade_4_subjects})

def edit_subject_detail(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    fields = Field.objects.filter(subject=subject)
    years = Year.objects.filter(questioninstance__question__subject=subject).distinct()

    return render(request, 'edit_subject_detail.html', {'subject': subject, 'fields': fields, 'years': years})

def edit_field_questions(request, field_id):
    field = get_object_or_404(Field, pk=field_id)
    questions = QuizQuestion.objects.filter(field=field)

    return render(request, 'edit_field_questions.html', {'field': field, 'questions': questions})

def edit_year_questions(request, subject_id, year_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    year = get_object_or_404(Year, pk=year_id)

    # QuestionInstance モデルを介して問題番号を取得
    question_instances = QuestionInstance.objects.filter(year=year, question__subject=subject).order_by('question_number')

    return render(request, 'edit_year_questions.html', {'subject': subject, 'year': year, 'question_instances': question_instances})
'''
def create_question(request):
    years = Year.objects.all()

    if request.method == 'POST':
        form = QuizQuestionForm(request.POST, request.FILES)
        if form.is_valid():
            # フォームからクリーンデータを取得
            subject = form.cleaned_data['subject']
            field = form.cleaned_data['field']
            question_text = form.cleaned_data['question_text']
            question_image = form.cleaned_data['question_image']
            explanation = form.cleaned_data['explanation']
            explanation_image = form.cleaned_data['explanation_image']

            # クイズの質問を保存
            quiz_question = QuizQuestion(
                subject=subject,
                field=field,
                question_text=question_text,
                question_image=question_image,
                explanation=explanation,
                explanation_image=explanation_image,
            )
            quiz_question.save()

            # 選択肢セットを保存
            index = 1
            while f'choice_texts_{index}' in request.POST:
                choice_text = request.POST[f'choice_texts_{index}']
                explanation_text = request.POST[f'explanation_texts_{index}']
                is_correct = request.POST[f'is_correct_values_{index}']

                choice = ChoiceExplanation(
                    question=quiz_question,
                    choice_text=choice_text,
                    explanation_text=explanation_text,
                    isCorrect=is_correct
                )
                choice.save()

                index += 1

            # 年・質問番号セットを保存
            index = 1
            while f'years_{index}' in request.POST:
                year_str = request.POST[f'years_{index}']  # 年の文字列を取得
                year_instance = Year.objects.get(year=year_str)  # 文字列からYearモデルのインスタンスを取得
                question_number = request.POST[f'question_numbers_{index}']

                question_instance = QuestionInstance(
                    question=quiz_question,
                    year=year_instance,  # Yearモデルのインスタンスを割り当てる
                    question_number=question_number
                )
                question_instance.save()

                index += 1

            return redirect('create_question')  # データが正常に保存された後のリダイレクト先URLを設定します
    else:
        form = QuizQuestionForm()

    return render(request, 'create_question.html', {'form': form, 'years': years})
'''

class QuizQuestionCreateView(CreateView):
    model = QuizQuestion
    form_class = QuizQuestionForm
    template_name = 'create_question.html'
    success_url = reverse_lazy('create_question')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['choice_formset'] = ChoiceExplanationFormSet(self.request.POST, prefix='choice', extra=5)
            context['question_formset'] = QuestionInstanceFormSet(self.request.POST, prefix='question', extra=1)
        else:
            context['choice_formset'] = ChoiceExplanationFormSet(prefix='choice')
            context['question_formset'] = QuestionInstanceFormSet(prefix='question')
            return context

    def form_valid(self, form):
        # クイズの質問を保存
        quiz_question = form.save()

        # 選択肢セットを保存
        choice_formset = ChoiceExplanationFormSet(self.request.POST, prefix='choice')
        if choice_formset.is_valid():
            for choice_form in choice_formset:
                choice = choice_form.save(commit=False)
                choice.question = quiz_question
                choice.save()

        # 年・質問番号セットを保存
        question_formset = QuestionInstanceFormSet(self.request.POST, prefix='question')
        if question_formset.is_valid():
            for question_form in question_formset:
                question = question_form.save(commit=False)
                question.question = quiz_question
                question.save()

        return super().form_valid(form)

class QuizQuestionUpdateView(UpdateView):
    model = QuizQuestion
    form_class = QuizQuestionForm
    template_name = 'update_question.html'
    success_url = reverse_lazy('field_questions')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['choice_formset'] = ChoiceExplanationFormSet2(self.request.POST, prefix='choice')
            context['question_formset'] = QuestionInstanceFormSet2(self.request.POST, prefix='question')
        else:
            context['choice_formset'] = ChoiceExplanationFormSet2(queryset=ChoiceExplanation.objects.filter(question=self.object), prefix='choice')
            context['question_formset'] = QuestionInstanceFormSet2(queryset=QuestionInstance.objects.filter(question=self.object), prefix='question')
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        choice_formset = context['choice_formset']
        question_formset = context['question_formset']

        if choice_formset.is_valid() and question_formset.is_valid():
            self.object = form.save()

            choices = choice_formset.save(commit=False)
            for choice in choices:
                choice.question = self.object
                choice.save()

            questions = question_formset.save(commit=False)
            for question in questions:
                question.question = self.object
                question.save()

            return super().form_valid(form)
        else:
            return super().form_invalid(form)

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        else:
            return resolve_url('update_question', self.object.id)

def get_fields(request):
    selected_subject = request.GET.get('subject')
    fields = Field.objects.filter(subject_id=selected_subject).values('id', 'name')
    return JsonResponse({'fields': list(fields)})

def answer_question(request, question_id):
    # 問題情報を取得
    question_pks = request.session.get('question_pks', [])

quiz/templates/base.html
</<!DOCTYPE html>
{% load static %}
{% load quiz_extra %}
<html lang="ja">
<head>
  {% block head %}{% endblock %}
  <meta charset="utf-8">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-Light bg-Light" aria-label="Ninth navbar example">
    <div class="container-xl">
      <a class="navbar-brand" href="#">過去問演習</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07XL" aria-controls="navbarsExample07XL" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarsExample07XL">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">ホーム</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'subject_list' %}">問題を見る</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="{% url 'create_question' %}">問題を追加する</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  {% block content %}{% endblock %}
</body>
</html>

quiz/templates/edit_field_questions.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load quiz_extra %}
{% load static %}
{% block head %}
<title>{{ field.name }}の問題</title>
<link rel="stylesheet" href="{% static 'css/list-groups.css' %}">
{% endblock %}
{% block content %}
<main>
  <section class="pt-5 text-center container">
    <div class="row pt-lg-5">
      <div class="col-lg-12 col-md-12 mx-auto">
        <h1 class="fw-light pb-3">{{ field.name }}の問題</h1>
      </div>
    </div>
  </section>
  <div class="d-flex mb-3 justify-content-center">
    <div class="list-group" style="max-width: 90%;!important">
      {% for question in questions %}
      <div>
        <a href="{% url 'update_question' question.pk %}?next={{ request.get_full_path }}" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">編集</a>
        <p>{{ question.question_text | linebreaksbr }}({% for year in question.questioninstance_set.all|dictsort:"year_id" %}{{ year.year }}-{{ year.question_number }}{% if not forloop.last %}, {% endif %}{% endfor %})</p>
        {% if question.question_image %}
        <img src="{{ question.question_image.url }}" alt="Question Image" style="cursor: pointer; max-width: 200px; margin-top: 10px;">
        {% endif %}
        <ul style="list-style: none; padding-left:0px;!important">
          {% for choice in question.choiceexplanation_set.all %}
          <li>{{ forloop.counter0|chr }}. {{ choice.choice_text }}</li>
          {% endfor %}
        </ul>
        <div style="text-align: right;">答.
          {% for choice in question.choiceexplanation_set.all %}
          {% if choice.isCorrect == True %}
          {{ forloop.counter0|chr }}
          {% endif %}
          {% empty %}
          {% endfor %}
        </div>
        <div style="text-align: right;">{% if question.explanation != "" and question.explanation != None %}{{ question.explanation }}{% endif %}</div>
        <div style="text-align: right;">
        <ul style="list-style: none; padding-left:0px;!important">
          {% for choice in question.choiceexplanation_set.all %}
          {% if choice.explanation_text != "" and choice.explanation_text != None %}
          <li>{{ forloop.counter0|chr }}. {{ choice.explanation_text }}</li>
          {% endif %}
          {% endfor %}
        </ul>
        </div>
      </div>
      <br>
      {% empty %}
      <p>問題がありません</p>
      {% endfor %}
    </div>
  </div>
</main>
<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript">
// ページを離れる前にスクロール位置を保存
window.addEventListener('beforeunload', function() {
  localStorage.setItem('scrollPosition', window.scrollY);
});

// ページに戻ったときにスクロール位置を復元
window.addEventListener('load', function() {
  var scrollPosition = localStorage.getItem('scrollPosition');
  if (scrollPosition) {
    window.scrollTo(0, scrollPosition);
  }
});
</script>
{% endblock %}

quiz/templates/update_question.html
{% extends "base.html" %}
{% load static %}
{% load quiz_extra %}
{% block content %}
<!-- create_question.html -->
<form method="post" id="quiz-form" enctype='multipart/form-data'>
  {% csrf_token %}
  <input type="submit" value="Save">
  <fieldset id="questions">
    <legend>Questions</legend>
    <div class="formset" id="questions-formset">
      {{ question_formset.management_form }}
      {% for question_form in question_formset %}
        <li style="list-style:none;" id="year-set-{{ forloop.counter0 }}">{{ question_form.as_table }}</li>
      {% endfor %}
    </div>
    <button type="button" id="add-question" data-formset="questions-formset">Add Question</button>
    <button type="button" id="delete-year" data-formset="questions-formset">Delete Question</button>
  </fieldset>

  {{ form.as_p }}

  <fieldset id="choices">
    <legend>Choices</legend>
    <div class="formset" id="choices-formset">
      {{ choice_formset.management_form }}
      {% for choice_form in choice_formset %}
        <li style="list-style:none;" id="choice-set-{{ forloop.counter0 }}">{{ choice_form.as_p }}</li>
      {% endfor %}
    </div>
    <button type="button" id="add-choice" data-formset="choices-formset">Add Choice</button>
    <button type="button" id="delete-choice" data-formset="choices-formset">Delete Choice</button>
  </fieldset>
  <input type="submit" value="Save">
</form>

<script>
  $(function(){
      var totalManageChoiceElement = $('input#id_choice-TOTAL_FORMS');
      var totalManageQuestionElement = $('input#id_question-TOTAL_FORMS');
      var currentChoiceCount = parseInt(totalManageChoiceElement.val());
      var currentQuestionCount = parseInt(totalManageQuestionElement.val());

      $('select#id_subject').on('change', function() {
          var selectedSubject = $(this).val();
          // subjectが変更されたら、それをフォームのhiddenフィールドに設定
          $('input#id_subject').val(selectedSubject);
      });

      $('button#add-choice').on('click', function(){
          var choiceItem = $('<li>', {
              id: 'choice-set-' + currentChoiceCount,
              style: "list-style:none;",
          });
          var choiceLabel = $('<label>', {
              for: 'id_choice-' + currentChoiceCount + '-choice_text',
              text: 'Choice text:',
          });
          var choiceElement = $('<input>', {
              type: 'text',
              name: 'choice-' + currentChoiceCount + '-choice_text',
              id: 'id_choice-' + currentChoiceCount + '-choice_text',
          });
          var explanationLabel = $('<label>', {
              for: 'id_choice-' + currentChoiceCount + '-explanation_text',
              text: 'Explanation text:',
          });
          var explanationElement = $('<input>', {
              type: 'text',
              name: 'choice-' + currentChoiceCount + '-explanation_text',
              id: 'id_choice-' + currentChoiceCount + '-explanation_text',
          });
          var correctLabel = $('<label>', {
              for: 'id_choice-' + currentChoiceCount + '-isCorrect',
              text: 'IsCorrect:',
          });
          var correctElement = $('<input>', {
              type: 'checkbox',
              name: 'choice-' + currentChoiceCount + '-isCorrect',
              id: 'id_choice-' + currentChoiceCount + '-isCorrect',
          });
          choiceItem.append(choiceLabel);
          choiceItem.append(choiceElement);
          choiceItem.append(explanationLabel);
          choiceItem.append(explanationElement);
          choiceItem.append(correctLabel);
          choiceItem.append(correctElement);
          $('div#choices-formset').append(choiceItem);
          currentChoiceCount += 1;
          totalManageChoiceElement.attr('value', currentChoiceCount);
      });

      $('button#delete-choice').on('click', function(){
          if (currentChoiceCount > 1) {
            var lastChoiceIndex = currentChoiceCount - 1;
            $('li#choice-set-' + lastChoiceIndex).remove();
            // フォームセット数を減少
            currentChoiceCount -= 1;
            totalManageChoiceElement.val(currentChoiceCount);
        } else {
            alert("最低1つの選択肢が必要です。"); // 1つの選択肢が必要な場合、アラートを表示するなどの処理を追加
        }
      });

      $('button#delete-year').on('click', function(){
          if (currentQuestionCount > 1) {
            var lastQuestionIndex = currentQuestionCount - 1;
            $('li#year-set-' + lastQuestionIndex).remove();
            // フォームセット数を減少
            currentQuestionCount -= 1;
            totalManageQuestionElement.val(currentQuestionCount);
        } else {
            alert("最低1つの年度が必要です。"); // 1つの選択肢が必要な場合、アラートを表示するなどの処理を追加
        }
      });

      $('button#add-question').on('click', function(){
          var yearItem = $('<li>', {
              id: 'year-set-' + currentQuestionCount,
              style: "list-style:none;",
          });
          var yearLabel = $('<label>', {
              for: 'id_question-' + currentQuestionCount + '-year',
              text: 'Year:',
          });

          // 年の選択肢を取得してドロップダウンメニューに追加する関数
          function addYearsToDropdown() {
              $.ajax({
                  url: '/get_years/',  // get_yearsビューのURLに合わせて変更
                  method: 'GET',
                  dataType: 'json',
                  success: function(data) {
                      var yearElement = $('<select>', {
                          name: 'question-' + (currentQuestionCount -1) + '-year',
                          id: 'id_question-' + (currentQuestionCount -1) + '-year',
                      });

                      // 取得した年のリストをドロップダウンメニューに追加
                      $.each(data.years, function(index, year) {
                          var optionElement = $('<option>', {
                              value: year.id,
                              text: year.year,
                          });
                          yearElement.append(optionElement);
                      });

                      var numberLabel = $('<label>', {
                          for: 'id_question-' + (currentQuestionCount -1) + '-year',  // 問題ごとにユニークなIDを設定
                          text: 'Question_number:',
                      });
                      var numberElement = $('<input>', {
                          type: 'number',
                          name: 'question-' + (currentQuestionCount -1) + '-question_number',  // 問題ごとにユニークな名前を設定
                          id: 'id_question-' + (currentQuestionCount -1) + '-question_number',
                      });

                      yearItem.append(yearLabel);
                      yearItem.append(yearElement);
                      yearItem.append(numberLabel);
                      yearItem.append(numberElement);
                      $('div#questions-formset').append(yearItem);
                  },
                  error: function() {
                      console.error('Failed to fetch years.');
                  }
              });
          }

          // 年の選択肢をドロップダウンメニューに追加
          addYearsToDropdown();

          currentQuestionCount += 1;
          totalManageQuestionElement.attr('value', currentQuestionCount);
      });
  });
</script>

{% endblock %}

quiz/templates/upload_form.html
{% extends "base.html" %}
{% load static %}
{% load quiz_extra %}
{% block head %}
    <title>Word文書アップロード</title>
{% endblock %}
{% block content %}
    <h2>Word文書をアップロードして内容を抽出</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
          <tr>
            <!-- 科目 -->
            <td class="right"><label for="{{ form.subject.id_for_label }}">科目</label></td>
            <td>{{ form.subject }}</td>
          </tr>
        </table>
        <input type="file" name="docx_file" accept=".docx" required>
        <br>
        <input type="submit" value="アップロード">
    </form>
{% endblock %}